name: flutter_base_framework_clean_architecture_with_mvvm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #For making HTTP request to APIs.
  http: ^1.1.0
  #For implementing BloC pattern
  flutter_bloc: ^8.1.3
  #For Comparing Complex Objects.
  equatable: ^2.0.5
  #For Local data storage.
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  page_transition: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  generate : true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserra
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
